# Generated by Django 4.2.7 on 2023-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartimePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('requirement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_start_work', models.DateTimeField()),
                ('date_end_work', models.DateTimeField()),
                ('description', models.TextField()),
                ('people', models.IntegerField()),
            ],
        ),
    ]
