# Generated by Django 4.2.7 on 2023-11-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartimePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_poster', models.URLField(blank=True, max_length=255)),
                ('requirement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_start_work', models.DateTimeField()),
                ('date_end_work', models.DateTimeField()),
                ('description', models.TextField()),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilesPartime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_work', models.IntegerField()),
                ('inspiration', models.TextField()),
                ('spacial_skill', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartimeProfileHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('working', 'Working'), ('pending', 'Pending'), ('reject', 'Reject')], max_length=20)),
                ('parttime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUPartime.partimepost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KUPartime.profilespartime')),
            ],
        ),
    ]
