# Generated by Django 4.2.7 on 2023-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUPartime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partimepost',
            name='image_poster',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
