# Generated by Django 4.2.7 on 2023-11-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KUPartime', '0002_partimepost_image_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilesPartime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_work', models.IntegerField()),
                ('inspiration', models.TextField()),
                ('spacial_skill', models.TextField()),
                ('parttime_history', models.ManyToManyField(blank=True, related_name='parttime_history', to='KUPartime.partimepost')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
