# Generated by Django 4.2.7 on 2023-11-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KUPartime', '0002_alter_partimeprofilehistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilespartime',
            old_name='user',
            new_name='user_id',
        ),
    ]
