# Generated by Django 4.2.7 on 2023-11-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUConnect', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='KUConnect.event'),
        ),
    ]
