# Generated by Django 4.2.7 on 2023-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUConnect', '0001_initial'),
        ('User', '0002_alter_userprofiles_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='favorites_events',
            field=models.ManyToManyField(blank=True, related_name='favorites_userprofiles', to='KUConnect.event'),
        ),
    ]
