# Generated by Django 4.2.7 on 2023-11-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userprofiles_advisor_userprofiles_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='user_permissions',
        ),
    ]
