# Generated by Django 4.2.7 on 2023-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofiles_favorites_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='events',
        ),
    ]
