# Generated by Django 4.2.7 on 2023-11-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_post', models.URLField()),
                ('type', models.CharField(blank=True, choices=[('Art', 'Art'), ('Music', 'Music'), ('Education', 'Education'), ('WELLNESS', 'Wellness'), ('Sciences', 'Sciences'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=100, null=True)),
                ('date_register', models.DateField()),
                ('date_end_register', models.DateField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('student_limit', models.IntegerField()),
                ('activity_point', models.IntegerField()),
                ('current_student', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image', to='KUConnect.event')),
            ],
        ),
    ]
